[2025-05-18T08:31:28.720+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-18T08:31:28.756+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_price_pipeline.ingest_csv_to_mysql manual__2025-05-18T08:26:25.029234+00:00 [queued]>
[2025-05-18T08:31:28.762+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_price_pipeline.ingest_csv_to_mysql manual__2025-05-18T08:26:25.029234+00:00 [queued]>
[2025-05-18T08:31:28.762+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-18T08:31:28.775+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): ingest_csv_to_mysql> on 2025-05-18 08:26:25.029234+00:00
[2025-05-18T08:31:28.791+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=287) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-18T08:31:28.790+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_price_pipeline', 'ingest_csv_to_mysql', 'manual__2025-05-18T08:26:25.029234+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/flight_price_pipeline.py', '--cfg-path', '/tmp/tmpau92sgzk']
[2025-05-18T08:31:28.792+0000] {standard_task_runner.py:64} INFO - Started process 289 to run task
[2025-05-18T08:31:28.792+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask ingest_csv_to_mysql
[2025-05-18T08:31:28.879+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_price_pipeline.ingest_csv_to_mysql manual__2025-05-18T08:26:25.029234+00:00 [running]> on host f2e665610613
[2025-05-18T08:31:28.988+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_price_pipeline' AIRFLOW_CTX_TASK_ID='ingest_csv_to_mysql' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T08:26:25.029234+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T08:26:25.029234+00:00'
[2025-05-18T08:31:28.990+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-18T08:31:29.018+0000] {ingestion.py:34} INFO - Starting ingestion process/opt/***/data/input/Flight_Price_Dataset_of_Bangladesh.csv to mysql table flight_prices_raw
[2025-05-18T08:31:29.590+0000] {ingestion.py:39} INFO - Read 57000 rows from csv
[2025-05-18T08:31:29.594+0000] {ingestion.py:68} ERROR - Failed to load data to mysql to MySQL: invalid literal for int() with base 10: 'None'
[2025-05-18T08:31:29.594+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-18T08:31:29.595+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/ingestion.py", line 64, in ingest_csv_to_mysql
    engine = create_engine(mysql_conn_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 514, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 738, in make_url
    return _parse_url(name_or_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 794, in _parse_url
    components["port"] = int(components["port"])
                         ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'None'
[2025-05-18T08:31:29.635+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=flight_price_pipeline, task_id=ingest_csv_to_mysql, run_id=manual__2025-05-18T08:26:25.029234+00:00, execution_date=20250518T082625, start_date=20250518T083128, end_date=20250518T083129
[2025-05-18T08:31:30.503+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task ingest_csv_to_mysql (invalid literal for int() with base 10: 'None'; 289)
[2025-05-18T08:31:30.564+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-05-18T08:31:30.608+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-18T08:31:30.612+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
