[2025-05-19T06:46:33.735+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-19T06:46:33.842+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_price_pipeline.transform_and_compute_kpis manual__2025-05-19T06:44:44.345225+00:00 [queued]>
[2025-05-19T06:46:33.857+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_price_pipeline.transform_and_compute_kpis manual__2025-05-19T06:44:44.345225+00:00 [queued]>
[2025-05-19T06:46:33.857+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2025-05-19T06:46:33.876+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_and_compute_kpis> on 2025-05-19 06:44:44.345225+00:00
[2025-05-19T06:46:33.954+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_price_pipeline', 'transform_and_compute_kpis', 'manual__2025-05-19T06:44:44.345225+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/flight_price_pipeline.py', '--cfg-path', '/tmp/tmpw83biv4h']
[2025-05-19T06:46:33.974+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask transform_and_compute_kpis
[2025-05-19T06:46:33.977+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=226) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-19T06:46:33.979+0000] {standard_task_runner.py:64} INFO - Started process 228 to run task
[2025-05-19T06:46:34.116+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_price_pipeline.transform_and_compute_kpis manual__2025-05-19T06:44:44.345225+00:00 [running]> on host fb87d03914c7
[2025-05-19T06:46:34.263+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_price_pipeline' AIRFLOW_CTX_TASK_ID='transform_and_compute_kpis' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T06:44:44.345225+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T06:44:44.345225+00:00'
[2025-05-19T06:46:34.270+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-19T06:46:34.323+0000] {transformation.py:36} INFO - Starting transformation and KPI computation for table flight_prices_raw
[2025-05-19T06:46:36.391+0000] {transformation.py:50} ERROR - Failed to read data from MySQL Table Select * from flight_prices_raw not found
[2025-05-19T06:46:36.392+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-19T06:46:36.393+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/transformation.py", line 47, in transform_and_compute_kpis
    df = pd.read_sql_table(f"Select * from {table_name}", con=engine)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 346, in read_sql_table
    raise ValueError(f"Table {table_name} not found")
ValueError: Table Select * from flight_prices_raw not found
[2025-05-19T06:46:36.438+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=flight_price_pipeline, task_id=transform_and_compute_kpis, run_id=manual__2025-05-19T06:44:44.345225+00:00, execution_date=20250519T064444, start_date=20250519T064633, end_date=20250519T064636
[2025-05-19T06:46:36.502+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task transform_and_compute_kpis (Table Select * from flight_prices_raw not found; 228)
[2025-05-19T06:46:36.565+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-05-19T06:46:36.629+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T06:46:36.631+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
